name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1.0.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Russian
          OPENAI_API_ENDPOINT: https://api.proxyapi.ru/openai/v1
          MODEL: gpt-3.5-turbo
          PROMPT: "You are an experienced Kotlin/Java developer responsible for reviewing pull requests. Your task is to review the following code for any misunderstandings or violations. Please refrain from commenting on aspects that are already functioning correctly. I am seeking constructive criticism and suggestions to enhance the code. Provide only useful and comprehensive feedback."