name: Gradle Package

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: build

      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish closeAndReleaseStagingRepository