name: Gradle Package

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: build

      - name: Restore gradle.properties
        uses: actions/checkout@v3
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
          echo ${GRADLE_PROPERTIES} > ~/.gradle/gradle.properties

      - name: Publish to Maven Central
        uses: gradle/gradle-build-action@v2.9.0
        run: ./gradlew publish closeAndReleaseStagingRepository